openapi: 3.2.0
info:
  title: Risk Parameters Margin Requirements Public Configuration API
  version: 3.60.0
  description: Operations about margin-requirements-public-configurations
servers:
- url: https://api.tastyworks.com
tags:
- name: margin-requirements-public-configuration
  description: Operations about margin-requirements-public-configurations
paths:
  /margin-requirements-public-configuration:
    get:
      description: Publicly accessible, read only margin configuration
      responses:
        '200':
          description: Publicly accessible, read only margin configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarginRequirementsGlobalConfiguration'
      tags:
      - margin-requirements-public-configuration
      operationId: getMarginRequirementsPublicConfiguration
      summary: Get margin requirements public configuration
      x-summary-source: derived
components:
  schemas:
    MarginRequirementsGlobalConfiguration:
      type: object
      properties:
        risk-free-rate:
          description: ''
          type: number
          format: double
      description: MarginRequirementsGlobalConfiguration model
