openapi: 3.2.0
info:
  title: Backtester Backend Available Dates API
  version: 1.0.0
  description: tastytrade options backtester
servers:
- url: https://backtester.vast.tastyworks.com
  description: Backtester API
tags:
- name: Available Dates
paths:
  /available-dates:
    get:
      summary: Available historical date ranges
      description: Available historical date ranges for every individual symbol
      operationId: GetAvailableDates
      responses:
        '200':
          description: List of available symbols and dates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableSymbolDates'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
      tags:
      - Available Dates
components:
  schemas:
    AvailableSymbolDates:
      type: object
      properties:
        symbol:
          type: string
        startDate:
          type: string
        endDate:
          type: string
  responses:
    '500':
      description: Failed to process request
    '400':
      description: Request included malformed input
